#!/bin/bash
#PBS -l walltime=24:00:00
#PBS -l vmem=3000MB
#PBS -q normal
#PBS -l ncpus=4
#PBS -l jobfs=1000MB
#PBS -l software=g09
#PBS -wd

module load gaussian

sh VAL5-A.com      
sh GLY3-A.com      
